### ISSUE TITLE
Prompt should not go to stdout

### ISSUE THREAD

**Issue by HenrikBengtsson** [wrathematics/getPass#1]
Currently, the prompt is outputted via stdout;

``` r
> capture.output(pwd <- getPass::getPass())
[1] "PASSWORD: "
```

This causes problems for report generators etc (who captures standard output).  I'd suggest to use standard error instead.

PS. See also https://stat.ethz.ch/pipermail/r-devel/2014-April/068931.html which discuss a "prompt" output stream, cf. `readline()`.

**Comment by wrathematics** [comment]
Great idea. I've updated it to use `REprintf()`.

I'm not sure how to access the prompt stream. I'll have to look a little closer at this later.

Thanks!

**Comment by wrathematics** [comment]
I've updated the method to print asterisks in the terminal, which is very simple with printing to stderr since it's unbuffered.  So I think I'll probably leave it at `REprintf()`, at least for now.

Closing issue.
