### ISSUE TITLE
Feature request: provide an unmasked-input option

### ISSUE THREAD

**Issue by zkurtz** [wrathematics/getPass#13]
`getPass` provides the only way I know to have an R script that is run from the command line prompt for user input. If you're willing to let people abuse your package for unintended use-cases, it would be very helpful if you could add an argument to allow intentional unmasking of input.  For example: https://stackoverflow.com/questions/45932404/r-script-with-user-input-from-command-line/48405624#48405624

**Comment by wrathematics** [comment]
I believe you can do this:

```r
userInput<-function(question) {
  cat(question)
  readLines(stdin(), n=1)
}
```

**Comment by zkurtz** [comment]
If I do 'Rscript toy.R' from my command line, where 'toy.R' is 

```
userInput = function(question) {
    readLines(stdin(), n=1)
}

x = userInput()
print(x)

```

then the script runs, but does not give me any opportunity to enter input.  `getPass` is different in this regard - I have no idea how you achieved this.

**Comment by wrathematics** [comment]
Weird, it works for me. What OS are you using?

Based on notes in `?readLines` and `?file`, maybe try this:

```r
userInput<-function(question) {
  cat(question)
  readLines(file("stdin"), n=1)
}
```

**Comment by zkurtz** [comment]
You are right!

I'm on OSX 10.12.6.
