### ISSUE TITLE
Add getUserText() function that mirrors getPass() without mask

### ISSUE THREAD

**Issue by nick-komick** [wrathematics/getPass#14]
Would you consider adding a `getUserText()` function that mirrors the `getPass_readline_masked` C function but with no mask?

I have found it challenging to use `readline` and `readLines(con=stdin())` to collect user input from the console on windows within a batch file.

A modified version of the getPass package with the "*" masked removed works well for getting user input from the console when a script is run from a windows batch file.

**Comment by wrathematics** [comment]
Have you tried `readLines(file("stdin"), n=1)` ? Using `file("stdin")` is different from `stdin()` (see `?readLines` and `?file`).

I'm not strictly opposed to adding functionality, but that base R solution should work.
